/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.deecaad.java-conventions")
}

dependencies {
    implementation(project(":MechanicsCore"))
    implementation("co.aikar:minecraft-timings:1.0.4")
}

tasks.test {
    useJUnitPlatform()
}

description = "WeaponMechanics"
