rootProject.name = "MechanicsMain"
include(":WeaponMechanics")
include(":MechanicsCore")
include(":WeaponMechanicsPlus")
include(":BuildMechanicsCore")
include(":BuildWeaponMechanics")

include(":MechanicsCoreCompatibility")
include(":WorldGuardV6")
include(":WorldGuardV7")
include(":CoreCompatibility_1_8_R3")
include(":CoreCompatibility_1_9_R2")
include(":CoreCompatibility_1_10_R1")
include(":CoreCompatibility_1_11_R1")
include(":CoreCompatibility_1_12_R1")
include(":CoreCompatibility_1_13_R2")
include(":CoreCompatibility_1_14_R1")
include(":CoreCompatibility_1_15_R1")
include(":CoreCompatibility_1_16_R3")
include(":CoreCompatibility_1_17_R1")
include(":CoreCompatibility_1_18_R1")

include(":WeaponMechanicsCompatibility")
include(":WeaponCompatibility_1_8_R3")
include(":WeaponCompatibility_1_9_R2")
include(":WeaponCompatibility_1_10_R1")
include(":WeaponCompatibility_1_11_R1")
include(":WeaponCompatibility_1_12_R1")
include(":WeaponCompatibility_1_13_R2")
include(":WeaponCompatibility_1_14_R1")
include(":WeaponCompatibility_1_15_R1")
include(":WeaponCompatibility_1_16_R3")
include(":WeaponCompatibility_1_17_R1")
include(":WeaponCompatibility_1_18_R1")


project(":WorldGuardV7").projectDir = file("MechanicsCoreCompatibility/WorldGuardV7")
project(":WorldGuardV6").projectDir = file("MechanicsCoreCompatibility/WorldGuardV6")

project(":CoreCompatibility_1_8_R3").projectDir  = file("MechanicsCoreCompatibility/CoreCompatibility_1_8_R3")
project(":CoreCompatibility_1_9_R2").projectDir  = file("MechanicsCoreCompatibility/CoreCompatibility_1_9_R2")
project(":CoreCompatibility_1_10_R1").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_10_R1")
project(":CoreCompatibility_1_11_R1").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_11_R1")
project(":CoreCompatibility_1_12_R1").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_12_R1")
project(":CoreCompatibility_1_13_R2").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_13_R2")
project(":CoreCompatibility_1_14_R1").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_14_R1")
project(":CoreCompatibility_1_15_R1").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_15_R1")
project(":CoreCompatibility_1_16_R3").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_16_R3")
project(":CoreCompatibility_1_17_R1").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_17_R1")
project(":CoreCompatibility_1_18_R1").projectDir = file("MechanicsCoreCompatibility/CoreCompatibility_1_18_R1")

project(":WeaponCompatibility_1_8_R3").projectDir  = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_8_R3")
project(":WeaponCompatibility_1_9_R2").projectDir  = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_9_R2")
project(":WeaponCompatibility_1_10_R1").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_10_R1")
project(":WeaponCompatibility_1_11_R1").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_11_R1")
project(":WeaponCompatibility_1_12_R1").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_12_R1")
project(":WeaponCompatibility_1_13_R2").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_13_R2")
project(":WeaponCompatibility_1_14_R1").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_14_R1")
project(":WeaponCompatibility_1_15_R1").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_15_R1")
project(":WeaponCompatibility_1_16_R3").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_16_R3")
project(":WeaponCompatibility_1_17_R1").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_17_R1")
project(":WeaponCompatibility_1_18_R1").projectDir = file("WeaponMechanicsCompatibility/WeaponCompatibility_1_18_R1")