/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "MechanicsMain"
include(":WeaponMechanics")
include(":WorldGuardV7")
include(":WorldGuardV6")
include(":MechanicsCore")
include(":MechanicsCoreCompatibility")
include(":WeaponMechanicsPlus")
include(":WeaponMechanicsCompatibility")
project(":WorldGuardV7").projectDir = file("MechanicsCoreCompatibility/WorldGuardV7")
project(":WorldGuardV6").projectDir = file("MechanicsCoreCompatibility/WorldGuardV6")

