/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.deecaad.java-conventions")
}

dependencies {
    implementation(project(":MechanicsCore"))
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.2.7")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.0.6")
}

description = "WorldGuardV7"
