name: Bug Report
description: Report any errors or bugs or other behavior related issues here.
labels: [ bug, needs triage ]
body:
  - type: checkboxes
    attributes:
      label: Has this issue already been reported? Did you ask for help before making this report?
      description: Please ask in the `#weaponmechanics-support` channel in our [discord](https://discord.gg/ERVgpfg)
      options:
        - label: I have searched the existing issues
          required: true
        - label: I have asked for help
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Use this config
        2. Spawn this weapon
        3. Shoot it at a player
        4. etc...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Frequency
      description: How often does this bug occur.
      placeholder: |
        It happens 100% of the time/It only happens sometimes during x/It rarely ever happens and is hard to reproduce/etc
    validations:
      required: true

  - type: textarea
    attributes:
      label: Version and Log
      description: |
        Please include a screenshot of your `/wm info` command, as well as your `latest.log` file.
        You **MUST** include **BOTH** your screenshot, and the log.
      placeholder: |
        To insert files:
        1. Try dragging and dropping files
        2. Try copying and pasting files
        3. If you are having trouble uploading files, use https://paste.gg
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Have a video? Screenshots? Any other important information? Please include it here.

        Tip: You can "drag and drop" files into the text box to upload images, logs, videos, or other files.
    validations:
      required: false
