blank_issues_enabled: true
contact_links:
  - name: WeaponMechanics Discord
    url: https://discord.gg/v5zfM9pgWT
    about: If you are having trouble with config, come and ask us in the weaponmechanics-support channel