/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.deecaad.java-conventions")
}

dependencies {
    implementation(project(":MechanicsCore"))
    implementation("com.google.code.findbugs:jsr305:1.3.9")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    compileOnly("me.clip:placeholderapi:2.10.10")
    compileOnly(files(file("../lib/nms/spigot-1.8.8.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.9.2.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.9.4.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.10.2.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.11.2.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.12.2.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.13.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.13.2.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.14.4.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.15.2.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.16.1.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.16.3.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.16.5.jar")))
    compileOnly(files(file("../lib/nms/spigot-1.17.1.jar")))
}

description = "MechanicsCoreCompatibility"
