/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.deecaad.java-conventions")
}

dependencies {
    implementation(project(":MechanicsCore"))
    implementation("com.google.code.findbugs:jsr305:1.3.9")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    compileOnly("me.clip:placeholderapi:2.10.10")
    compileOnly(files(file("../lib/nms/S1_8_R3.jar")))
    compileOnly(files(file("../lib/nms/S1_9_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_9_R2.jar")))
    compileOnly(files(file("../lib/nms/S1_10_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_11_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_12_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_13_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_13_R2.jar")))
    compileOnly(files(file("../lib/nms/S1_14_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_15_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_16_R1.jar")))
    compileOnly(files(file("../lib/nms/S1_16_R2.jar")))
    compileOnly(files(file("../lib/nms/S1_16_R3.jar")))
    compileOnly(files(file("../lib/nms/S1_17_R1.jar")))
    compileOnly(files(file("../lib/nms/CraftBukkitLib.jar")))
}

description = "MechanicsCoreCompatibility"
