/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.deecaad.java-conventions")
}

dependencies {
    api("org.spigotmc:spigot-api:1.18-R0.1-SNAPSHOT")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    compileOnly("me.clip:placeholderapi:2.10.10")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")
    compileOnly("com.mojang:authlib:1.5.21")
    compileOnly("io.netty:netty-all:4.0.23.Final")
}

tasks.test {
    useJUnitPlatform()
}

description = "MechanicsCore"
