/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("me.deecaad.java-conventions")
}

dependencies {
    implementation(project(":WeaponMechanics"))
    implementation(project(":MechanicsCore"))
}

description = "WeaponMechanicsCompatibility"
